sudo: required
language: ruby
rvm:
  - "2.0.0"
  - ruby-head
env:
  - "PGVERSION=10.0-1-linux-x64 PATH=\"/opt/PostgreSQL/10/bin:$PATH\""
  - "PGVERSION=9.3.19-1-linux-x64 PATH=\"/opt/PostgreSQL/9.3/bin:$PATH\""
before_install:
  - gem install bundler
  - bundle install
  # Download and install postgresql version to test against in /opt
  - |
    wget http://get.enterprisedb.com/postgresql/postgresql-$PGVERSION.run && \
      chmod +x postgresql-$PGVERSION.run && \
      sudo ./postgresql-$PGVERSION.run --extract-only 1 --mode unattended
script: rake test
